name: Build and Push Docker Image

on:
  push:
    branches: [ main, add-multi-arch ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Generate Version
      id: version
      run: |
        VERSION=$(date +%Y%m%d)-$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=version::$VERSION"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and Push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        push: true
        platforms: linux/arm64
        tags: austinarcher/flask-app:${{ steps.version.outputs.version }}

    # Only needed if using buildx
    - name: Pull Docker Image
      run: docker pull --platform linux/arm64 austinarcher/flask-app:${{ steps.version.outputs.version }}

    - name: Get Image Digest to Sign
      run: |
        IMAGE_SHA=$(docker inspect austinarcher/flask-app:${{ steps.version.outputs.version }} | jq -r '.[].Id')
        IMAGE_NAME=austinarcher/flask-app
        SIGNING_TARGET="$IMAGE_NAME"@"$IMAGE_SHA"
        echo ARTIFACT="$SIGNING_TARGET" >> $GITHUB_ENV

    - name: Container sign
      uses: endorlabs/github-action/sign@aa5139fcbfa6faa120afc511f0678f81485e83bc
      with:
        namespace: "david-learn"
        artifact_name: ${{ env.ARTIFACT }}

    - name: Push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: austinarcher/flask-app:latest
